name: Build and Package

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build for AWS
        run: |
          mv src/index-aws.ts src/index.ts
          npm run build
          cp package.json dist/
          cd dist
          npm install --production --legacy-peer-deps
          zip -r ../deploy-aws.zip .

      - name: Build for Huawei Cloud
        run: |
          mv src/index-huawei-cloud.ts src/index.ts
          npm run clean
          tsc --module CommonJS --target ES6 --esModuleInterop true
          cp package.json dist/
          cd dist
          npm install --production --legacy-peer-deps
          rm package.json package-lock.json
          zip -r ../deploy-huawei-cloud.zip .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset AWS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVERCHAN_SENDKEY: ${{ secrets.SERVERCHAN_SENDKEY }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./deploy-aws.zip
          asset_name: deploy-aws.zip
          asset_content_type: application/zip

      - name: Upload Release Asset Huawei Cloud
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./deploy-huawei-cloud.zip
          asset_name: deploy-huawei-cloud.zip
          asset_content_type: application/zip
